#!/usr/bin/env bash
set -euo pipefail

BINARY_NAME="firefox-pwa"
# Must live in omarchy's bin: walker/elephant run with the systemd user PATH,
# which contains ~/.local/share/omarchy/bin but NOT ~/.local/bin, so a copy
# in ~/.local/bin is invisible to apps launched from the omarchy menu.
INSTALL_DIR="$HOME/.local/share/omarchy/bin"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SOURCE="$SCRIPT_DIR/$BINARY_NAME"
FIREFOX_PROFILE_NAME="pwas"

# Check source binary exists
if [[ ! -f "$SOURCE" ]]; then
  echo "Error: '$BINARY_NAME' not found next to this script (expected at $SOURCE)"
  exit 1
fi

# Check firefox is available
if ! command -v firefox &>/dev/null; then
  echo "Error: 'firefox' not found in PATH. Cannot create profile."
  exit 1
fi

# Create install dir if needed
mkdir -p "$INSTALL_DIR"

# Copy and make executable
cp "$SOURCE" "$INSTALL_DIR/$BINARY_NAME"
chmod +x "$INSTALL_DIR/$BINARY_NAME"
echo "Installed: $INSTALL_DIR/$BINARY_NAME"

# Warn if not in PATH
if ! echo "$PATH" | grep -q "$INSTALL_DIR"; then
  echo "Warning: '$INSTALL_DIR' is not in your PATH."
fi

# Drop the copy older versions of this script left in ~/.local/bin so a stale
# binary can't shadow the installed one in interactive shells
if [[ -f "$HOME/.local/bin/$BINARY_NAME" ]]; then
  rm "$HOME/.local/bin/$BINARY_NAME"
  echo "Removed stale: $HOME/.local/bin/$BINARY_NAME"
fi

# Create Firefox profile "pwas" if it doesn't already exist
PROFILES_INI="$HOME/.mozilla/firefox/profiles.ini"
if [[ -f "$PROFILES_INI" ]] && grep -q "Name=$FIREFOX_PROFILE_NAME" "$PROFILES_INI"; then
  echo "Firefox profile '$FIREFOX_PROFILE_NAME' already exists, skipping."
else
  echo "Creating Firefox profile '$FIREFOX_PROFILE_NAME'..."
  firefox --headless --createProfile "$FIREFOX_PROFILE_NAME $HOME/.mozilla/firefox/profile.$FIREFOX_PROFILE_NAME" 2>/dev/null
  echo "Firefox profile '$FIREFOX_PROFILE_NAME' created."
fi

# Replace omarchy's launcher so web apps created through the omarchy menu
# (elephant/walker) open via firefox-pwa instead of requiring a Chromium
# browser. Omarchy updates restore the stock script, so this must re-run
# after every update (pre-stow.sh handles that).
OMARCHY_BIN="$HOME/.local/share/omarchy/bin"
LAUNCHER_NAME="omarchy-launch-webapp"
LAUNCHER_SOURCE="$SCRIPT_DIR/$LAUNCHER_NAME"

if [[ ! -f "$LAUNCHER_SOURCE" ]]; then
  echo "Error: '$LAUNCHER_NAME' not found next to this script (expected at $LAUNCHER_SOURCE)"
  exit 1
fi

if [[ -d "$OMARCHY_BIN" ]]; then
  cp "$LAUNCHER_SOURCE" "$OMARCHY_BIN/$LAUNCHER_NAME"
  chmod +x "$OMARCHY_BIN/$LAUNCHER_NAME"
  echo "Patched: $OMARCHY_BIN/$LAUNCHER_NAME"
else
  echo "Warning: '$OMARCHY_BIN' not found, skipping $LAUNCHER_NAME patch."
fi

# Self-healing across omarchy updates.
# `omarchy update` overwrites everything in ~/.local/share/omarchy/bin with the
# upstream sources, silently reverting the launcher patch above and breaking
# every web app until setup is re-run by hand. Omarchy runs `omarchy-hook
# post-update` at the end of each update, which executes every non-.sample file
# in ~/.config/omarchy/hooks/post-update.d/. Drop a hook there that re-runs this
# very script, so the patch re-applies itself automatically after each update on
# any machine where setup has been run.
SELF="$SCRIPT_DIR/$(basename "${BASH_SOURCE[0]}")"
HOOK_DIR="$HOME/.config/omarchy/hooks/post-update.d"
HOOK_FILE="$HOOK_DIR/patch-webapp"
mkdir -p "$HOOK_DIR"
cat >"$HOOK_FILE" <<EOF
#!/bin/bash
# Auto-generated by patch-webapp.sh — do not edit; changes are overwritten.
# Re-applies the Firefox web-app launcher patch after an omarchy update
# restores the stock (Chromium-only) omarchy-launch-webapp. No-op if the
# dotfiles repo has moved or been removed.
[[ -x "$SELF" ]] && exec "$SELF"
EOF
chmod +x "$HOOK_FILE"
echo "Installed post-update hook: $HOOK_FILE"

